application: clicksaju-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /clicksaju\.appcache
  static_files: clicksaju.appcache
  mime_type: text/cache-manifest
  upload: clicksaju\.appcache
  expiration: "0s"

- url: /.*
  script: clicksaju.app
